services:
  dev:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: tail -f /dev/null

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: oms_development
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
