services:
  dev:
    build:
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: postgres://app:5432@db/oms_development
      APP_PORT: 3000
    ports:
      - 127.0.0.1:3000:3000
    command: tail -f /dev/null

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_DB: oms_development
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./docs:/app
    environment:
      - SWAGGER_JSON=/app/apidocs.yml
    ports:
      - 127.0.0.1:8080:8080
